### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference goroutine

### ISSUE THREAD

**Issue by Alex-ley-scrub** [cristianoliveira/ergo#144]
system info:
```
brew --version
Homebrew 4.0.28
Homebrew/homebrew-core (git revision 10a8cea9523; last commit 2023-03-08)
```
and
```
sw_vers
ProductName:		macOS
ProductVersion:		13.4.1
BuildVersion:		22F82
```

install method:
```
brew tap cristianoliveira/tap
brew install ergo
cd ~/repos/web-server
touch .ergo
ergo setup osx # doesn't work
```

This appears to work for me to set the proxy up:
```
sudo networksetup -setproxyautodiscovery Wi-Fi on
sudo networksetup -setautoproxystate Wi-Fi on
sudo networksetup -setautoproxyurl Wi-Fi 'http://localhost:2000/proxy.pac'
```
and this to remove those settings (note the space not an empty string, empty string failed for me):
```
sudo networksetup -setproxyautodiscovery Wi-Fi off
sudo networksetup -setautoproxyurl Wi-Fi ' '
sudo networksetup -setautoproxystate Wi-Fi off
```

then launch (my real domain replaced with my-domain):
```
export ERGO_DOMAIN=".test"
ergo add my-domain 127.0.0.1:3000
ergo run
```

I get this error message when navigating to http://my-domain.test/
```
Ergo Proxy listening on port 2000 for domains .test
[2023-07-08 20:04:45] GET http://my-domain.test/ HTTP/1.1 
-------------- parts [[my-domain.test my-domain my-domain]]
2023/07/08 20:04:45 http: panic serving 127.0.0.1:62955: runtime error: invalid memory address or nil pointer dereference
goroutine 58 [running]:
net/http.(*conn).serve.func1()
	/Users/runner/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1825 +0xbf
panic({0x128fa40, 0x14de680})
	/Users/runner/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:844 +0x258
github.com/cristianoliveira/ergo/proxy.NewErgoProxy.func1(0xc0002ac800)
	/Users/runner/work/ergo/ergo/proxy/proxy.go:31 +0x1e0
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc000026280, {0x13536a0?, 0xc0002a2460}, 0xc000394200)
	/Users/runner/hostedtoolcache/go/1.18.10/x64/src/net/http/httputil/reverseproxy.go:252 +0x306
net/http.(*ServeMux).ServeHTTP(0x0?, {0x13536a0, 0xc0002a2460}, 0xc000394200)
	/Users/runner/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc00038a1b0?}, {0x13536a0, 0xc0002a2460}, 0xc000394200)
	/Users/runner/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0002881e0, {0x13538c8, 0xc00007eff0})
	/Users/runner/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/Users/runner/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x4db
```

**Comment by Alex-ley-scrub** [comment]
I installed it via brew 3 days ago so I assume the latest:
`v0.3.0`

**Comment by cristianoliveira** [comment]
I found the issue here. You are adding a service without a protocol.

Instead of
```sh
ergo add my-domain 127.0.0.1:3000
```
You must provide the protocol for the service.
```sh
ergo add my-domain http://127.0.0.1:3000
```

I see that isn't intuitive, so probably we must either validate or assume a default "http".
