### ISSUE TITLE
bug: Error when running ergo without command

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/ergo#64]
I am having an error when running ergo without providing a command.

Expected behavior:
Show USAGE

Actual behavior:
```
ergo
panic: runtime error: index out of range

goroutine 1 [running]:
main.command(0x12da13e)
        /Users/cristianoliveira/go/src/github.com/cristianoliveira/ergo/main.go:45 +0xc8c
main.main()
        /Users/cristianoliveira/go/src/github.com/cristianoliveira/ergo/main.go:127 +0xb5
```
The problem is here. We should look if `os.Args` has more than 1 item before creating the command
```go
func command() func() {
	config := proxy.NewConfig()
>>>	command := flag.NewFlagSet(os.Args[1], flag.ExitOnError)
	configFile := command.String("config", "./.ergo", "Set the services file")
	command.Parse(os.Args[2:])
```

It should be easy to solve.

**Please also provide a test for it**

**Comment by pzelnip** [comment]
I'd like to take a stab at this.
